### ISSUE TITLE
meson:ImportError: libffi.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-core#3094]
Checking dependencies for meson 
Building meson version 0.61.2
Traceback (most recent call last):
  File "/usr/src/meson-0.61.2/setup.py", line 23, in <module>
    from setuptools import setup
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 32, in <module>
    from setuptools import windows_support
  File "/usr/lib/python3.10/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

**Comment by Ratler** [comment]
You need to run lunar fix. libffi changed the so-name version.

**Comment by lhw828** [comment]
> You need to run lunar fix. libffi changed the so-name version.

Lunar fix is stuck here https://github.com/lunar-linux/moonbase-other/issues/1868
